apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
    - port: 80
      targetPort: 3100
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: learnk8sgcr.io/kuberenetes-01-basic/order-service
          ports:
            - containerPort: 3100
          env:
            - name: REDIS_HOST
              value: myredis
            - name: REDIS_PORT
              value: 6379
            - name: ORDER_SERVICE_PORT
              value: 3100
          imagePullPolicy: Always